language: cpp

compiler:
    - gcc

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
    sources:
      - ubuntu-toolchain-r-test

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - test/testAVLTree